### ISSUE TITLE
How to support vendoring?

### ISSUE THREAD

**Issue by dragonsinth** [fullstorydev/gorepoman#1]
Do we need vendoring?  How should we support it?

**Comment by jhump** [comment]
Proposal:

1. Look for manifest file in current directory (or in directory given in command-line argument), instead of requiring it be in `$GOPATH/src`.
2. Always manage and store the dependencies in a `vendor` folder that is a sibling of the manifest file.
3. Add a command-line flag for bootstrapping -- e.g. no manifest file exists, so the flag tells gorepoman to create one in the current directory (or the directory named by other argument).

This simple scheme allows managing deps at any level of the source tree with very little change to existing logic.

It can be put behind a flag, though I think we'd actually want the reverse: vendoring becomes the default behavior, and an option to skip the `vendor` folder (the current behavior) gets put behind a flag.

**Comment by jhump** [comment]
I'm calling this one closed, as of #3
